modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-v3"

[[mods]]
modId="directionoptimizer"
version="${file.jarVersion}"
displayName="DirectionOptimizer"
authors="Team Potato"
description='''

'''